"""add attachment and link to assignment

Revision ID: 3f35c9b277e0
Revises: 8f4f273153f9
Create Date: 2025-12-14 20:04:18.818765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f35c9b277e0'
down_revision = '8f4f273153f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignments', sa.Column('attachment_url', sa.Text(), nullable=True))
    op.add_column('assignments', sa.Column('link_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assignments', 'link_url')
    op.drop_column('assignments', 'attachment_url')
    # ### end Alembic commands ###
