"""add due_date column

Revision ID: 8f4f273153f9
Revises: 7ec765273804
Create Date: 2025-12-14 19:12:37.335875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f4f273153f9'
down_revision = '7ec765273804'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('enrollments_student_id_course_id_key'), 'enrollments', type_='unique')
    op.drop_constraint(op.f('lesson_completions_student_id_lesson_id_key'), 'lesson_completions', type_='unique')
    op.alter_column('lessons', 'sort_order',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('modules', 'sort_order',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_unique_constraint(op.f('uq_users_email'), 'users', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_users_email'), 'users', type_='unique')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('modules', 'sort_order',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('lessons', 'sort_order',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.create_unique_constraint(op.f('lesson_completions_student_id_lesson_id_key'), 'lesson_completions', ['student_id', 'lesson_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('enrollments_student_id_course_id_key'), 'enrollments', ['student_id', 'course_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
